### PR TITLE
Fix timezone list and slider component

### PR DESCRIPTION
**Pull request by zulhailmie**
This fixes the timezone list in EmulationStation settings by hardcoding the list into GuiMenu.cpp.
Requires updating tz package to version 2021a on 351ELEC as the list is based on the latest tz version.

### CODE REVIEW

**Comment by zulhailmie** [comment]
Added a fix for the slider component.
This fixes the out-of-place slider knob when the minimum value is set to anything more than a single digit value.
Please see attached images for better graphical explanation :P

Minimum value: 5 (single digit)
5_minimum_marked

Minimum value: 15 (double digit)
15_minimum_marked

**Comment by konsumschaf** [comment]
Could you share the problem you are fixing by hardcoding the timezone information? Generally it would be easier to maintain if the information stays in one place and does not have to be in sync with another package - wouldn't it be easier to import the information?

**Comment by zulhailmie** [comment]
> Could you share the problem you are fixing by hardcoding the timezone information? Generally it would be easier to maintain if the information stays in one place and does not have to be in sync with another package - wouldn't it be easier to import the information?

A couple of the timezones are not displayed correctly in ES. Few of them overlaps with another timezone, rendering them unusable.

I've already checked through the imported information in zone1970.tab for typos and there are none.
The problem is how the import is being handled in GuiMenu.cpp. Possibly due to limitations of stringstream or getline? I'm not sure.. tried few other workarounds to import the information but to no success.

ES already depend on the tz package for information.
https://github.com/351ELEC/351elec-emulationstation/blob/main/es-app/src/guis/GuiMenu.cpp at line 1341
https://github.com/351ELEC/351ELEC/blob/main/packages/351elec/sources/scripts/emuelec-utils at line 218
https://github.com/351ELEC/351ELEC/blob/main/packages/sysutils/tz/package.mk at line 18

I've only updated the package, truncated, sort the information and hardcoded them.

Here's some images of the problem I'm trying to fix:

**Comment by zulhailmie** [comment]
Will commit the discussed fix with @konsumschaf to https://github.com/351ELEC/351ELEC/pull/338
Closing this PR.

**Pull request closed without merging**
